language: node_js

node_js:
- '6'

install:
- npm install

script:
- npm run build

cache:
  directories:
  - node_modules

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    skip_cleanup: true
    local-dir: build
    on:
      branch: master